// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8dbbsbSzIoV1GRITlMjoRaGOv-kkJDYM',
    appId: '1:63321503325:web:c57c90eeaa77923e2d7fb4',
    messagingSenderId: '63321503325',
    projectId: 'tickets-project-4d6b4',
    authDomain: 'tickets-project-4d6b4.firebaseapp.com',
    databaseURL: 'https://tickets-project-4d6b4-default-rtdb.firebaseio.com',
    storageBucket: 'tickets-project-4d6b4.firebasestorage.app',
    measurementId: 'G-C4JSR28X1J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDS_chTqQNuK9Ebh9ptclvopbBNnh5Agew',
    appId: '1:63321503325:android:1a561c28cabeb9872d7fb4',
    messagingSenderId: '63321503325',
    projectId: 'tickets-project-4d6b4',
    databaseURL: 'https://tickets-project-4d6b4-default-rtdb.firebaseio.com',
    storageBucket: 'tickets-project-4d6b4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbBThWaXDEwtsM_w_lwgRkE_XEW7IwqA',
    appId: '1:63321503325:ios:99c67e188c9a164b2d7fb4',
    messagingSenderId: '63321503325',
    projectId: 'tickets-project-4d6b4',
    databaseURL: 'https://tickets-project-4d6b4-default-rtdb.firebaseio.com',
    storageBucket: 'tickets-project-4d6b4.firebasestorage.app',
    iosBundleId: 'com.example.cimatickProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYbBThWaXDEwtsM_w_lwgRkE_XEW7IwqA',
    appId: '1:63321503325:ios:99c67e188c9a164b2d7fb4',
    messagingSenderId: '63321503325',
    projectId: 'tickets-project-4d6b4',
    databaseURL: 'https://tickets-project-4d6b4-default-rtdb.firebaseio.com',
    storageBucket: 'tickets-project-4d6b4.firebasestorage.app',
    iosBundleId: 'com.example.cimatickProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8dbbsbSzIoV1GRITlMjoRaGOv-kkJDYM',
    appId: '1:63321503325:web:273adbbad771a61d2d7fb4',
    messagingSenderId: '63321503325',
    projectId: 'tickets-project-4d6b4',
    authDomain: 'tickets-project-4d6b4.firebaseapp.com',
    databaseURL: 'https://tickets-project-4d6b4-default-rtdb.firebaseio.com',
    storageBucket: 'tickets-project-4d6b4.firebasestorage.app',
    measurementId: 'G-5NGHKTXDS5',
  );
}
